version: "3.7"
volumes:
  data:
services:
  manhua:
    image: 520xcy/comicsviewer:latest
    container_name: manhua
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - 漫画目录:/workdir/contents
    ports:
      - 8181:18181
      - 8182:18182