version: "3.7"
volumes:
  data:
services:
  manhua:
    image: 520xcy/comicsviewer:alpine
    container_name: manhua
    environment:
      - PUID=1000
      - GUID=1000
    volumes:
      - 漫画目录:/workdir/contents
      - data:/workdir/data
    ports:
      - 8181:18181